ALTER TABLE account DROP COLUMN password;
ALTER TABLE account DROP COLUMN namespace;
ALTER TABLE account DROP COLUMN ttl;
ALTER TABLE account ADD UNIQUE (email);
ALTER TABLE account ADD COLUMN image VARCHAR NOT NULL;
ALTER TABLE account ADD COLUMN social_platform VARCHAR NOT NULL;
ALTER TABLE account ADD COLUMN social_id VARCHAR NOT NULL;
ALTER TABLE account ADD COLUMN social_name VARCHAR NOT NULL;
