db_url = "postgres://postgres:secret@127.0.0.1:5432/delta_sharing"
server_addr = "http://127.0.0.1:8080"
server_bind = "127.0.0.1:8080"
signed_url_ttl = 28800
secret = "your secret here"
hasher = "sha256"
use_json_log = false
log_filter = "warn,delta_sharing=debug"
